name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      selectedTag:
        description: "Select the tag to filter tests"
        required: true
        default: "@Smoke"
        type: choice
        options:
          - "@Smoke"
          - "@Regression"
          - "@BestSeller"
          - "@ShoppingToCart"
          - "@Sanity"
          - "@E2E"
      selectedBranch:
        description: "Select the branch to run the workflow on"
        required: true
        default: "main"
        type: choice
        options:
          - "master"
          - "newbranch"
          - "feature-branch-1"
          - "feature-branch-2"

jobs:
  build:

    runs-on: Cicd123

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.selectedBranch }} # Checkout the selected branch

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn clean test -D"dataproviderthreadcount"="3" -D"cucumber.filter.tags"="${{ inputs.selectedTag }}"
      #mvn clean test -D"dataproviderthreadcount"="3" -D"cucumber.filter.tags"="@BestSeller"

    - name: Generate Cucumber HTML Report
      run: mvn verify -D"cucumber.report.output.name"="cucumber-html-report"

    - name: Archive Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/site

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
