name: Java CI with Maven

on:
  # Schedule the workflow to run at 9:00 PM IST (3:30 PM UTC)
  schedule:
    - cron: "30 15 * * *"

  workflow_dispatch:  # Manual trigger for flexibility
    inputs:
      selectedTag:
        description: "Select the tag to filter tests"
        required: true
        default: "@Smoke"
        type: choice
        options:
          - "@Smoke"
          - "@Regression"
          - "@BestSeller"
          - "@ShoppingToCart"
          - "@Sanity"
          - "@E2E"
      selectedBranch:
        description: "Select the branch to run the workflow on"
        required: true
        default: "main"
        type: choice
        options:
          - "master"
          - "newbranch"
          - "feature-branch-1"
          - "feature-branch-2"

jobs:
  build:

    runs-on: Cicd1234

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: master  # Always use the master branch for scheduled runs

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn clean test -D"dataproviderthreadcount"="3" -D"cucumber.filter.tags"="@ShoppingToCart"

    - name: Generate Cucumber HTML Report
      run: mvn verify -DskipTests=true -D"cucumber.report.output.name"="cucumber-html-report"

   # - name: Archive Cucumber Reports
    #  uses: actions/upload-artifact@v3
    #  with:
     #   name: cucumber-reports
     #   path: target/cucumber-reports
